name: Publish Lambda
on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - "lambdas/**"
      - ".github/workflows/lambdas.yaml"

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOY_AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOY_AWS_ACCESS_SECRET }}
  CLERK_API_KEY: ${{ secrets.CLERK_API_KEY }}
  CLERK_DEV_API_KEY: ${{ secrets.CLERK_DEV_API_KEY }}
  ENCRYPTION_SECRET: ${{ secrets.ENCRYPTION_SECRET }}
  ENCRYPTION_SECRET_DEV: ${{ secrets.ENCRYPTION_SECRET_DEV }}
  ROAMJS_EMAIL: support@roamjs.com
  ROAMJS_DEVELOPER_TOKEN: ${{ secrets.ROAMJS_DEVELOPER_TOKEN }}
  DROPBOX_CLIENT_SECRET: ${{ secrets.DROPBOX_CLIENT_SECRET }}
  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
  SLACK_CLIENT_SECRET: ${{ secrets.SLACK_CLIENT_SECRET }}
  ROAM_API_TOKEN: ${{ secrets.ROAM_API_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: install
        run: npm install
      - name: Deploy
        run: npx ts-node ./scripts/lambdas.ts
        env:
          NODE_ENV: production
